@URL=http://localhost/EcommerceBE/categoria

GET {{URL}}/get.php

###

POST {{URL}}/create.php
Content-Type: application/json

{
    "nome": "MMORPG"
} 

###

GET {{URL}}/delete.php?id=5

###

POST {{URL}}/update.php?id=3
Content-Type: application/json

{
    "nome": "MMO"
}