@URL = https://localhost/EcommerceBE/compra

###
GET {{URL}}/get.php

###
POST {{URL}}/create.php
Content-Type: application/json

{
    "id_usuario": 1,
    "itens": [
        {
            "id_produto": 1,
            "quantidade": 2
        },
        {
            "id_produto": 2,
            "quantidade": 1
        }
    ],
    "valor": 100,
    "data": "2021-05-05"
}

###
GET {{URL}}/delete.php?id=4

###
POST {{URL}}/update.php?id=5
Content-Type: application/json

{
    "id_usuario": "1",
    "valor": "110",
    "data": "2021-05-05"
}